import type { Metadata } from "next";
import "../../styles/globals.scss";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Navbar from "@/components/Layout/Navbar/Navbar";
import Footer from "@/components/Layout/Footer/Footer";
import Body from "@/components/Layout/Body/Body";
import { AuthProvider } from "@/contexts/AuthContext";
import SocialAuthSync from "@/components/LogicComponents/SocialAuthSync";
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/Providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`@/messages/${locale}.json`)).default;

  return (
    <html lang={locale}>
      <body>
        <Providers locale={locale} messages={messages}>
          <Navbar />
          <Body>{children}</Body>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
